services:
  paymentgatewayservice:
    image: paymentgatewayservice
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      STRIPE_WEBHOOK_SECRET: "${STRIPE_WEBHOOK_SECRET:?STRIPE_WEBHOOK_SECRET is required}"
    ports:
      - 3000:3000
